"""Console helpers for Windows-safe script output."""

import sys


def configure_utf8_output():
    """Prevent Unicode generated by LLMs from crashing print() on Windows."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass
